"""
Phase 1: Bronze Enhancement & Feature Optimization

This script implements Phase 1 of the ML project roadmap:
- 1.1: 163rd Place Integration (data pipeline, tanh function, evaluation protocol)
- 1.2: Feature Analysis from Advanced Solutions (261-feature and 1187-feature pipelines)
- 1.3: Feature Importance Analysis (SHAP analysis)
- 1.4: Feature Optimization (ablations, window sizes, lag depths, interactions)

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

# Try to import SHAP for feature importance analysis
try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False
    print("SHAP not available - feature importance analysis will be limited")

# Try to import optuna for feature optimization
try:
    import optuna
    OPTUNA_AVAILABLE = True
except ImportError:
    OPTUNA_AVAILABLE = False
    print("Optuna not available - feature optimization will use grid search")

from itertools import product

# ============================================================================
# CONFIGURATION
# ============================================================================

class Config:
    # Data settings
    DATA_PATH = "train.csv"
    TEST_SIZE = 0.20
    RANDOM_STATE = 42
    EXCLUDE_LAST_N_DAYS = 180  # 163rd place protocol
    
    # Target
    TARGET = 'market_forward_excess_returns'
    
    # 163rd Place settings
    TANH_BOUND = 0.006
    TANH_SCALE = 3.0
    VOL_WINDOW = 20
    MAX_VOL_RATIO = 1.20
    BASE_MULTIPLIER = 80.0
    
    # Model settings
    LGBM_PARAMS = {
        'objective': 'regression',
        'metric': 'rmse',
        'boosting_type': 'gbdt',
        'num_leaves': 31,
        'max_depth': -1,
        'learning_rate': 0.01,
        'n_estimators': 5000,
        'min_child_samples': 20,
        'reg_alpha': 0.0,
        'reg_lambda': 0.0,
        'random_state': RANDOM_STATE,
        'verbose': -1,
        'n_jobs': -1,
    }
    
    EARLY_STOPPING_ROUNDS = 100
    VALIDATION_FRACTION = 0.10
    
    # Feature engineering configurations from both pipelines
    # 261-feature pipeline specs (ht-final-v1.ipynb)
    LAG_SPECS_261 = {
        "V13": [1, 2, 3],
        "M4": [1, 2, 3, 5],
        "V7": [1, 2],
        "E19": [1, 2, 5, 90],
        "P12": [20],
        "I4": [20],
        "M5": [180],
        "P10": [2],
        "M12": [90, 10],
        "V9": [1, 3],
        "M3": [2],
        "P5": [1, 3],
        "P4": [5],
        "S8": [1],
    }
    
    ROLLING_MEAN_SPECS_261 = {
        "V13": [2, 3],
        "M4": [2, 3],
        "E19": [2, 3],
        "S2": [3],
        "P10": [5],
        "P11": [5],
        "M11": [180],
        "V9": [2],
        "I4": [20],
        "M7": [60],
        "M1": [2],
    }
    
    ROLLING_STD_SPECS_261 = {
        "E19": [3],
        "I2": [2, 3],
        "P6": [2],
        "M4": [2],
        "S5": [2],
        "S10": [2],
        "P2": [10],
        "M1": [3],
    }
    
    EMA_SPECS_261 = {
        "M4": [2, 3, 5, 10, 20],
        "E19": [2, 3, 5],
        "V13": [3, 5],
        "M3": [2, 10],
        "V9": [2, 3, 10],
        "P7": [10, 180],
        "M2": [5, 10],
    }
    
    # 1187-feature pipeline specs (htmp-optuna-v8-final-cpu.ipynb)
    LAGS_1187 = [1, 2, 5, 10]  # Applied to all base features
    WINDOWS_1187 = [5, 10]  # Rolling window sizes
    STATS_1187 = ['mean', 'std', 'max']  # Rolling statistics
    
    # For feature optimization testing
    TEST_LAG_DEPTHS = list(range(1, 21))  # Test 1-20 day lags
    TEST_WINDOW_SIZES = [3, 5, 10, 15, 20, 25, 30, 60]  # Test different window sizes

config = Config()


# ============================================================================
# 1.1 163RD PLACE INTEGRATION
# ============================================================================

def convert_ret_to_signal_163rd(x, bound=0.006, scale=3.0):
    """
    163rd Place exact tanh function implementation.
    This is their signal conversion function.
    """
    x_clipped = np.clip(x, -bound, bound)
    x_norm = x_clipped / bound
    x_scaled = x_norm * scale
    return np.tanh(x_scaled) + 1.0


def calculate_volatility_multiplier_163rd(predictions, window=20):
    """
    163rd Place volatility multiplier calculation.
    """
    pred_series = pd.Series(predictions)
    rolling_std = pred_series.rolling(window=window, min_periods=1).std()
    rolling_std = rolling_std.fillna(1.0)
    
    overall_std = np.std(predictions)
    if overall_std < 1e-10:
        return pd.Series([1.0] * len(predictions))
    
    raw_multiplier = overall_std / (rolling_std + 1e-10)
    return raw_multiplier


def calculate_allocation_163rd(predictions, backtest_era, config):
    """
    163rd Place allocation calculation with volatility constraint.
    """
    vol_multiplier = calculate_volatility_multiplier_163rd(predictions, window=config.VOL_WINDOW)
    scaled_predictions = predictions * vol_multiplier.values
    signals = convert_ret_to_signal_163rd(scaled_predictions, config.TANH_BOUND, config.TANH_SCALE)
    
    # Constrain to [0, MAX_VOL_RATIO] to ensure volatility ratio <= MAX_VOL_RATIO
    return np.clip(signals, 0.0, config.MAX_VOL_RATIO)


def prepare_data_163rd(data_path, config):
    """
    163rd Place data pipeline: No imputation, drop missing records.
    Exclude last 180 days for evaluation protocol.
    """
    print("\n" + "="*70)
    print("1.1: 163RD PLACE DATA PIPELINE")
    print("="*70)
    
    # Load and sort data chronologically
    df = pd.read_csv(data_path)
    df = df.sort_values(by="date_id").reset_index(drop=True)
    
    print(f"Original data shape: {df.shape}")
    
    # No imputation - drop missing records (163rd place approach)
    initial_len = len(df)
    df = df.dropna()
    print(f"Dropped {initial_len - len(df)} rows with missing values")
    
    # Create volatility proxy
    v_cols = [col for col in df.columns if col.startswith('V')]
    if v_cols:
        df['vol_proxy'] = df[v_cols].abs().mean(axis=1)
    else:
        df['vol_proxy'] = 1.0
    
    # Define targets and features
    targets = ['forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
    exclude_cols = ['date_id'] + targets + ['vol_proxy']
    feature_cols = [col for col in df.columns if col not in exclude_cols]
    
    print(f"Final feature count: {len(feature_cols)}")
    
    # 163rd place protocol: Exclude last 180 days for training
    TRAIN_END = len(df) - config.EXCLUDE_LAST_N_DAYS
    train_era = df.iloc[:TRAIN_END].copy()
    backtest_era = df.iloc[TRAIN_END:].copy()
    
    print(f"Training samples: {len(train_era)}")
    print(f"Backtest samples: {len(backtest_era)}")
    print(f"Excluded last {config.EXCLUDE_LAST_N_DAYS} days for evaluation")
    
    # Prepare feature matrices
    X_train = train_era[feature_cols]
    X_backtest = backtest_era[feature_cols]
    
    # Standardize features (163rd place uses standardization)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_backtest_scaled = scaler.transform(X_backtest)
    
    return {
        'df': df,
        'train_era': train_era,
        'backtest_era': backtest_era,
        'X_train_scaled': X_train_scaled,
        'X_backtest_scaled': X_backtest_scaled,
        'feature_cols': feature_cols,
        'scaler': scaler,
        'targets': targets,
        'TRAIN_END': TRAIN_END
    }


def evaluate_strategy_163rd(backtest_era, predictions, data, config, strategy_name="163rd Place"):
    """
    Evaluate strategy using 163rd Place evaluation protocol.
    """
    # Calculate allocation
    allocation = calculate_allocation_163rd(predictions, backtest_era, config)
    
    # Calculate strategy returns
    market_daily_return = backtest_era['forward_returns'].values
    strategy_daily_return = allocation * market_daily_return
    
    # Information Coefficient
    actual_returns = backtest_era[config.TARGET].values
    ic = np.corrcoef(predictions, actual_returns)[0, 1]
    
    # Annualized returns
    ann_market_return = np.mean(market_daily_return) * 252 * 100
    ann_strategy_return = np.mean(strategy_daily_return) * 252 * 100
    
    # Annualized volatility
    ann_market_vol = np.std(market_daily_return) * np.sqrt(252) * 100
    ann_strategy_vol = np.std(strategy_daily_return) * np.sqrt(252) * 100
    
    # Volatility ratio
    vol_ratio = ann_strategy_vol / ann_market_vol if ann_market_vol > 0 else 0
    vol_pass = vol_ratio <= config.MAX_VOL_RATIO
    vol_ratio_status = "(PASS)" if vol_pass else "(FAIL)"
    
    # Sharpe Ratio
    market_sharpe = ann_market_return / ann_market_vol if ann_market_vol > 0 else 0
    strategy_sharpe = ann_strategy_return / ann_strategy_vol if ann_strategy_vol > 0 else 0
    
    # Net Alpha
    net_alpha = ann_strategy_return - ann_market_return
    
    # Competition-like score
    score = strategy_sharpe * (1.0 - max(0, vol_ratio - config.MAX_VOL_RATIO) / 2.0)
    
    return {
        'name': strategy_name,
        'ic': ic,
        'ann_market_return': ann_market_return,
        'ann_strategy_return': ann_strategy_return,
        'ann_market_vol': ann_market_vol,
        'ann_strategy_vol': ann_strategy_vol,
        'vol_ratio': vol_ratio,
        'vol_ratio_status': vol_ratio_status,
        'vol_pass': vol_pass,
        'market_sharpe': market_sharpe,
        'strategy_sharpe': strategy_sharpe,
        'net_alpha': net_alpha,
        'score': score,
        'allocation': allocation,
        'predictions': predictions
    }


# ============================================================================
# 1.2 FEATURE ANALYSIS FROM ADVANCED SOLUTIONS
# ============================================================================

def create_lag_features_261(df, lag_specs=None):
    """
    Create lag features based on 261-feature pipeline specifications.
    """
    print("Creating 261-feature pipeline lag features...")
    
    if lag_specs is None:
        lag_specs = config.LAG_SPECS_261
    
    for base_col, lags in lag_specs.items():
        if base_col in df.columns:
            for lag in lags:
                col_name = f"{base_col}_lag_{lag}"
                df[col_name] = df[base_col].shift(lag)
    
    print(f"Added lag features for {len(lag_specs)} base features")
    return df


def create_rolling_features_261(df, mean_specs=None, std_specs=None):
    """
    Create rolling window features based on 261-feature pipeline specifications.
    """
    print("Creating 261-feature pipeline rolling features...")
    
    if mean_specs is None:
        mean_specs = config.ROLLING_MEAN_SPECS_261
    if std_specs is None:
        std_specs = config.ROLLING_STD_SPECS_261
    
    # Rolling mean features
    for base_col, windows in mean_specs.items():
        if base_col in df.columns:
            for window in windows:
                col_name = f"{base_col}_roll_mean_{window}"
                df[col_name] = df[base_col].rolling(window=window, min_periods=1).mean()
    
    # Rolling std features
    for base_col, windows in std_specs.items():
        if base_col in df.columns:
            for window in windows:
                col_name = f"{base_col}_roll_std_{window}"
                df[col_name] = df[base_col].rolling(window=window, min_periods=1).std()
    
    print(f"Added rolling features for mean and std specs")
    return df


def create_ema_features_261(df, ema_specs=None):
    """
    Create EMA features based on 261-feature pipeline specifications.
    """
    print("Creating 261-feature pipeline EMA features...")
    
    if ema_specs is None:
        ema_specs = config.EMA_SPECS_261
    
    for base_col, windows in ema_specs.items():
        if base_col in df.columns:
            for window in windows:
                col_name = f"{base_col}_ema_{window}"
                df[col_name] = df[base_col].ewm(span=window, adjust=False).mean()
    
    print(f"Added EMA features for {len(ema_specs)} base features")
    return df


def create_interaction_features_261(df):
    """
    Create interaction features (DIV_PAIRS, MINUS_PAIRS, PRODUCT_PAIRS) from 261-feature pipeline.
    """
    print("Creating 261-feature pipeline interaction features...")
    
    # DIV_PAIRS from ht-final-v1.ipynb
    DIV_PAIRS = [
        ("E19", "P4"), ("P6", "M12"), ("V13", "P4"), ("P8", "P13"), ("V7", "P4"),
        ("S5", "P8"), ("I2", "E16"), ("M3", "P10"), ("V13", "M9"), ("P2", "E17"),
        ("M4", "I5"), ("E19", "P3"), ("V13", "S9"), ("M1", "P8"), ("V9", "M9"),
        ("E3", "V10"), ("M9", "V10"), ("M4", "P6"), ("S5", "P7"),
    ]
    
    # MINUS_PAIRS from ht-final-v1.ipynb
    MINUS_PAIRS = [
        ("P8", "M2"), ("E19", "P6"), ("V13", "E19"), ("V7", "I2"), ("V13", "S2"),
        ("V9", "E3"), ("V13", "M1"), ("S9", "E2"), ("E19", "I2"), ("S12", "P2"),
        ("M4", "M3"), ("V7", "M3"), ("V7", "P2"), ("V9", "M1"), ("V7", "S2"),
        ("V9", "P2"), ("P5", "P13"), ("E19", "P7"), ("M4", "E19"), ("S8", "M2"),
    ]
    
    # PRODUCT_PAIRS from ht-final-v1.ipynb
    PRODUCT_PAIRS = [
        ("V13", "E19"), ("V13", "M4"), ("V9", "E3"), ("V7", "P2"), ("E19", "P10"),
    ]
    
    # Create DIV features
    for col1, col2 in DIV_PAIRS:
        if col1 in df.columns and col2 in df.columns:
            col_name = f"{col1}_div_{col2}"
            df[col_name] = df[col1] / (df[col2] + 1e-6)
    
    # Create MINUS features
    for col1, col2 in MINUS_PAIRS:
        if col1 in df.columns and col2 in df.columns:
            col_name = f"{col1}_minus_{col2}"
            df[col_name] = df[col1] - df[col2]
    
    # Create PRODUCT features
    for col1, col2 in PRODUCT_PAIRS:
        if col1 in df.columns and col2 in df.columns:
            col_name = f"{col1}_prod_{col2}"
            df[col_name] = df[col1] * df[col2]
    
    print(f"Added DIV_PAIRS ({len(DIV_PAIRS)}), MINUS_PAIRS ({len(MINUS_PAIRS)}), PRODUCT_PAIRS ({len(PRODUCT_PAIRS)}) features")
    return df


def create_square_features_261(df):
    """
    Create square features from 261-feature pipeline.
    """
    print("Creating 261-feature pipeline square features...")
    
    BASE_TO_SQ = {
        "V9": "V9_sq", "M4": "M4_sq", "E19": "E19_sq", "P10": "P10_sq",
        "P7": "P7_sq", "V13": "V13_sq", "V7": "V7_sq", "E2": "E2_sq",
        "S5": "S5_sq", "M3": "M3_sq", "P6": "P6_sq", "P2": "P2_sq", "I2": "I2_sq",
    }
    
    for base_col, new_name in BASE_TO_SQ.items():
        if base_col in df.columns:
            df[new_name] = df[base_col] ** 2
    
    print(f"Added {len(BASE_TO_SQ)} square features")
    return df


def create_zscore_features_261(df):
    """
    Create z-score features from 261-feature pipeline.
    """
    print("Creating 261-feature pipeline z-score features...")
    
    # Use rolling std specs for z-score calculation
    eps = 1e-6
    for base_col, windows in config.ROLLING_STD_SPECS_261.items():
        if base_col in df.columns:
            x = df[base_col]
            for window in windows:
                roll_mean = x.rolling(window=window, min_periods=1).mean()
                roll_std = x.rolling(window=window, min_periods=1).std()
                col_name = f"{base_col}_roll_z_{window}"
                df[col_name] = (x - roll_mean) / (roll_std + eps)
    
    print(f"Added z-score features for {len(config.ROLLING_STD_SPECS_261)} base features")
    return df


def create_relative_features_261(df):
    """
    Create relative features (div and minus rolling mean) from 261-feature pipeline.
    """
    print("Creating 261-feature pipeline relative features...")
    
    # Use rolling mean specs for relative features
    for base_col, windows in config.ROLLING_MEAN_SPECS_261.items():
        if base_col in df.columns:
            x = df[base_col]
            for window in windows:
                roll_mean = x.rolling(window=window, min_periods=1).mean()
                
                # DIV rolling mean
                col_name = f"{base_col}_div_roll_mean_{window}"
                df[col_name] = x / (roll_mean + 1e-6)
                
                # MINUS rolling mean
                col_name = f"{base_col}_minus_roll_mean_{window}"
                df[col_name] = x - roll_mean
    
    print(f"Added relative features for {len(config.ROLLING_MEAN_SPECS_261)} base features")
    return df


def create_full_261_feature_pipeline(df):
    """
    Create complete 261-feature pipeline from ht-final-v1.ipynb.
    """
    print("\n" + "="*70)
    print("1.2: CREATING 261-FEATURE PIPELINE")
    print("="*70)
    
    # Step 1: Square features
    df = create_square_features_261(df)
    
    # Step 2: Lag features
    df = create_lag_features_261(df)
    
    # Step 3: Rolling features (mean, std)
    df = create_rolling_features_261(df)
    
    # Step 4: EMA features
    df = create_ema_features_261(df)
    
    # Step 5: Z-score features
    df = create_zscore_features_261(df)
    
    # Step 6: Relative features (div and minus rolling mean)
    df = create_relative_features_261(df)
    
    # Step 7: Interaction features
    df = create_interaction_features_261(df)
    
    # Count total features added
    original_cols = set(df.columns) - {col for col in df.columns if '_lag_' in col or '_roll_' in col or '_ema_' in col or '_div_' in col or '_minus_' in col or '_prod_' in col or '_sq' in col or 'roll_z_' in col}
    total_features = len(df.columns)
    print(f"Total features after 261-feature pipeline: {total_features}")
    
    return df


def create_lag_features_1187(df, base_features=None, lags=None):
    """
    Create lag features based on 1187-feature pipeline specifications.
    """
    print("Creating 1187-feature pipeline lag features...")
    
    if lags is None:
        lags = config.LAGS_1187
    
    if base_features is None:
        # Get all base features (excluding date_id, targets, etc.)
        exclude = ['date_id', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
        base_features = [col for col in df.columns if col not in exclude]
    
    for base_col in base_features:
        if base_col in df.columns:
            for lag in lags:
                col_name = f"{base_col}_L{lag}"
                df[col_name] = df[base_col].shift(lag)
    
    print(f"Added lag features for {len(base_features)} base features with {len(lags)} lags each")
    return df


def create_rolling_features_1187(df, base_features=None, windows=None, stats=None):
    """
    Create rolling window features based on 1187-feature pipeline specifications.
    """
    print("Creating 1187-feature pipeline rolling features...")
    
    if windows is None:
        windows = config.WINDOWS_1187
    if stats is None:
        stats = config.STATS_1187
    if base_features is None:
        exclude = ['date_id', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
        base_features = [col for col in df.columns if col not in exclude]
    
    for base_col in base_features:
        if base_col in df.columns:
            for window in windows:
                for stat in stats:
                    if stat == 'mean':
                        col_name = f"{base_col}_RMean{window}"
                        df[col_name] = df[base_col].rolling(window=window, min_periods=1).mean()
                    elif stat == 'std':
                        col_name = f"{base_col}_RStd{window}"
                        df[col_name] = df[base_col].rolling(window=window, min_periods=1).std()
                    elif stat == 'max':
                        col_name = f"{base_col}_RMax{window}"
                        df[col_name] = df[base_col].rolling(window=window, min_periods=1).max()
    
    print(f"Added rolling features: {len(base_features)} base features x {len(windows)} windows x {len(stats)} stats = {len(base_features) * len(windows) * len(stats)} features")
    return df


def create_rank_zscore_features_1187(df, base_features=None):
    """
    Create rank and z-score features based on 1187-feature pipeline specifications.
    """
    print("Creating 1187-feature pipeline rank and z-score features...")
    
    if base_features is None:
        exclude = ['date_id', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
        base_features = [col for col in df.columns if col not in exclude]
    
    rank_cols = []
    zscore_cols = []
    
    for base_col in base_features:
        if base_col in df.columns:
            # Rank features
            rank_col = f"{base_col}_RANK"
            df[rank_col] = df[base_col].rank(method='min')
            rank_cols.append(rank_col)
            
            # Z-score features
            mean_c = df[base_col].mean()
            std_c = df[base_col].std()
            std_c_safe = std_c if abs(std_c) > 1e-6 else 1e-6
            zscore_col = f"{base_col}_ZSCORE"
            df[zscore_col] = (df[base_col] - mean_c) / std_c_safe
            zscore_cols.append(zscore_col)
    
    print(f"Added {len(rank_cols)} rank features and {len(zscore_cols)} z-score features")
    return df, rank_cols, zscore_cols


def create_interaction_features_1187(df, rank_cols=None, zscore_cols=None):
    """
    Create interaction features based on 1187-feature pipeline specifications.
    """
    print("Creating 1187-feature pipeline interaction features...")
    
    if rank_cols is None or zscore_cols is None:
        _, rank_cols, zscore_cols = create_rank_zscore_features_1187(df)
    
    from itertools import product
    
    # 1. Targeted interactions for specific features (M4, M1, E1, V2)
    targeted_features = ['M4', 'M1', 'E1', 'V2']
    for c in targeted_features:
        if c in df.columns and f'{c}_RANK' in df.columns:
            # c * c_RANK
            col_name = f"{c}_x_{c}_RANK"
            df[col_name] = df[c] * df[f'{c}_RANK']
            # c / (c_RANK + 1e-6)
            col_name = f"{c}_div_{c}_RANK"
            df[col_name] = df[c] / (df[f'{c}_RANK'] + 1e-6)
    
    # 2. Rank * Rank (Unique Pairs) - limit to first 12 for computational efficiency
    target_rank_cols = rank_cols[:12]
    rank_rank_count = 0
    for i, r_col1 in enumerate(target_rank_cols):
        for j, r_col2 in enumerate(target_rank_cols):
            if i < j:  # Unique pairs only
                c1 = r_col1.split('_')[0]
                c2 = r_col2.split('_')[0]
                if c1 < c2:  # Ensure consistent naming
                    col_name = f"{c1}R_x_{c2}R"
                    df[col_name] = df[r_col1] * df[r_col2]
                    rank_rank_count += 1
    
    # 3. Rank * ZScore - limit to first 9
    target_zscore_cols = zscore_cols[:9]
    target_rank_cols_9 = rank_cols[:9]
    rank_zscore_count = 0
    for r_col, z_col in zip(target_rank_cols_9, target_zscore_cols):
        col_name = f"{r_col}_x_{z_col}"
        df[col_name] = df[r_col] * df[z_col]
        rank_zscore_count += 1
    
    print(f"Added targeted interactions ({len(targeted_features) * 2}), Rank*Rank ({rank_rank_count}), Rank*ZScore ({rank_zscore_count}) features")
    return df


def create_full_1187_feature_pipeline(df):
    """
    Create complete 1187-feature pipeline from htmp-optuna-v8-final-cpu.ipynb.
    """
    print("\n" + "="*70)
    print("1.2: CREATING 1187-FEATURE PIPELINE")
    print("="*70)
    
    # Get base features
    exclude = ['date_id', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
    base_features = [col for col in df.columns if col not in exclude]
    
    # Step 1: Lag features
    df = create_lag_features_1187(df, base_features)
    
    # Step 2: Rolling window features
    df = create_rolling_features_1187(df, base_features)
    
    # Step 3: Rank and Z-score features
    df, rank_cols, zscore_cols = create_rank_zscore_features_1187(df, base_features)
    
    # Step 4: Interaction features
    df = create_interaction_features_1187(df, rank_cols, zscore_cols)
    
    # Count total features
    total_features = len(df.columns)
    print(f"Total features after 1187-feature pipeline: {total_features}")
    
    return df


# ============================================================================
# 1.3 FEATURE IMPORTANCE ANALYSIS (SHAP)
# ============================================================================

def run_shap_analysis(model, X_train, feature_names, model_type="regression"):
    """
    Run SHAP analysis on a trained model to understand feature importance.
    """
    if not SHAP_AVAILABLE:
        print("SHAP not available. Skipping SHAP analysis.")
        return None
    
    print(f"\nRunning SHAP analysis for {model_type} model...")
    
    try:
        # Create SHAP explainer based on model type
        if isinstance(model, lgb.LGBMRegressor) or isinstance(model, lgb.LGBMClassifier):
            explainer = shap.TreeExplainer(model)
        elif isinstance(model, (RandomForestRegressor, RandomForestClassifier)):
            explainer = shap.TreeExplainer(model)
        elif isinstance(model, (Ridge, LogisticRegression)):
            explainer = shap.LinearExplainer(model, X_train)
        else:
            print(f"No SHAP explainer available for model type: {type(model)}")
            return None
        
        # Calculate SHAP values
        if len(X_train) > 1000:  # Use sample for large datasets
            X_sample = X_train[:1000]
            print(f"Using sample of {len(X_sample)} instances for SHAP calculation")
        else:
            X_sample = X_train
        
        shap_values = explainer.shap_values(X_sample)
        
        # For binary classification, shap_values might be a list
        if isinstance(shap_values, list):
            shap_values = shap_values[0] if len(shap_values) > 0 else shap_values
        
        # Create SHAP summary
        shap_df = pd.DataFrame({
            'feature': feature_names,
            'shap_importance': np.abs(shap_values).mean(axis=0)
        }).sort_values('shap_importance', ascending=False)
        
        print(f"SHAP analysis complete. Top 10 features:")
        print(shap_df.head(10).to_string(index=False))
        
        return shap_df
        
    except Exception as e:
        print(f"Error in SHAP analysis: {e}")
        return None


def compare_feature_importance_across_models(X_train, y_train, feature_names):
    """
    Compare feature importance across different model types.
    """
    print("\n" + "="*70)
    print("1.3: FEATURE IMPORTANCE ANALYSIS ACROSS MODELS")
    print("="*70)
    
    models_to_test = [
        ("LightGBM", lgb.LGBMRegressor(**config.LGBM_PARAMS)),
        ("Ridge", Ridge(alpha=500.0, random_state=config.RANDOM_STATE)),
        ("RandomForest", RandomForestRegressor(n_estimators=100, random_state=config.RANDOM_STATE)),
    ]
    
    all_importances = {}
    
    for model_name, model in models_to_test:
        print(f"\nTraining {model_name} model...")
        model.fit(X_train, y_train)
        
        # Get feature importances from the model
        if hasattr(model, 'feature_importances_'):
            model_importances = model.feature_importances_
        elif hasattr(model, 'coef_'):
            model_importances = np.abs(model.coef_)
        else:
            print(f"No feature importance available for {model_name}")
            continue
        
        importance_df = pd.DataFrame({
            'feature': feature_names,
            'importance': model_importances
        }).sort_values('importance', ascending=False)
        
        all_importances[model_name] = importance_df
        
        print(f"{model_name} - Top 10 features:")
        print(importance_df.head(10).to_string(index=False))
        
        # Run SHAP analysis for this model
        if SHAP_AVAILABLE:
            shap_df = run_shap_analysis(model, X_train, feature_names, model_name)
            if shap_df is not None:
                all_importances[f"{model_name}_SHAP"] = shap_df
    
    # Identify overlapping high-importance features
    print(f"\n" + "="*70)
    print("OVERLAPPING HIGH-IMPORTANCE FEATURES")
    print("="*70)
    
    # Get top 20 features from each model
    top_features_by_model = {}
    for model_name, importance_df in all_importances.items():
        if not model_name.endswith('_SHAP'):
            top_20 = importance_df['feature'].head(20).tolist()
            top_features_by_model[model_name] = set(top_20)
    
    # Find intersection of top features across models
    common_top_features = set.intersection(*top_features_by_model.values())
    print(f"Features in top 20 for ALL models: {len(common_top_features)}")
    print(f"Common features: {sorted(list(common_top_features))[:20]}")  # Limit to first 20
    
    # Create feature importance hierarchy
    print(f"\nCreating feature importance hierarchy...")
    all_features = set()
    for importance_df in all_importances.values():
        all_features.update(importance_df['feature'].tolist())
    
    # Calculate average rank across models
    feature_ranks = {}
    for feature in all_features:
        ranks = []
        for model_name, importance_df in all_importances.items():
            if not model_name.endswith('_SHAP'):
                try:
                    rank = importance_df[importance_df['feature'] == feature].index[0]
                    ranks.append(rank)
                except (IndexError, KeyError):
                    ranks.append(len(importance_df))  # Assign worst rank if not found
        feature_ranks[feature] = np.mean(ranks)
    
    hierarchy_df = pd.DataFrame({
        'feature': list(feature_ranks.keys()),
        'avg_rank': list(feature_ranks.values())
    }).sort_values('avg_rank')
    
    print("Feature Importance Hierarchy (by average rank):")
    print(hierarchy_df.head(20).to_string(index=False))
    
    return all_importances, hierarchy_df


# ============================================================================
# 1.4 FEATURE OPTIMIZATION
# ============================================================================

def test_feature_ablations(X_train, y_train, X_backtest, y_backtest, feature_names, model_class=lgb.LGBMRegressor, model_params=None):
    """
    Test feature ablations: Remove categories to measure impact.
    """
    print("\n" + "="*70)
    print("1.4: FEATURE ABLATION STUDY")
    print("="*70)
    
    if model_params is None:
        model_params = config.LGBM_PARAMS
    
    # Categorize features
    feature_categories = {}
    for feature in feature_names:
        prefix = feature.split('_')[0][0]  # Get first character (D, E, M, P, S, V, I)
        if prefix not in feature_categories:
            feature_categories[prefix] = []
        feature_categories[prefix].append(feature)
    
    print(f"Feature categories: {list(feature_categories.keys())}")
    for cat, feats in feature_categories.items():
        print(f"  {cat}: {len(feats)} features")
    
    # Train baseline model
    print(f"\nTraining baseline model...")
    model = model_class(**model_params)
    model.fit(X_train, y_train)
    baseline_score = model.score(X_backtest, y_backtest)
    baseline_predictions = model.predict(X_backtest)
    baseline_ic = np.corrcoef(baseline_predictions, y_backtest)[0, 1]
    print(f"Baseline score: {baseline_score:.4f}, IC: {baseline_ic:.4f}")
    
    # Test ablation for each category
    ablation_results = []
    for category, features in feature_categories.items():
        if len(features) < 5:  # Skip small categories
            continue
            
        print(f"\nTesting ablation: removing {category} ({len(features)} features)")
        
        # Create feature mask
        mask = [True] * len(feature_names)
        for feature in features:
            try:
                idx = feature_names.index(feature)
                mask[idx] = False
            except ValueError:
                continue
        
        X_train_ablated = X_train[:, mask]
        X_backtest_ablated = X_backtest[:, mask]
        
        # Train model without this category
        model_ablated = model_class(**model_params)
        model_ablated.fit(X_train_ablated, y_train)
        
        ablated_score = model_ablated.score(X_backtest_ablated, y_backtest)
        ablated_predictions = model_ablated.predict(X_backtest_ablated)
        ablated_ic = np.corrcoef(ablated_predictions, y_backtest)[0, 1]
        
        impact = baseline_score - ablated_score
        ic_impact = baseline_ic - ablated_ic
        
        result = {
            'category': category,
            'features_removed': len(features),
            'baseline_score': baseline_score,
            'ablated_score': ablated_score,
            'score_impact': impact,
            'baseline_ic': baseline_ic,
            'ablated_ic': ablated_ic,
            'ic_impact': ic_impact
        }
        
        ablation_results.append(result)
        print(f"  Score impact: {impact:+.4f}, IC impact: {ic_impact:+.4f}")
    
    # Sort by impact
    ablation_df = pd.DataFrame(ablation_results).sort_values('score_impact', ascending=False)
    print(f"\nFeature ablation results:")
    print(ablation_df.to_string(index=False))
    
    return ablation_df


def test_lag_depths(X_train, y_train, X_backtest, y_backtest, feature_names, base_features, model_class=lgb.LGBMRegressor, model_params=None):
    """
    Test different lag depths for key features.
    """
    print("\n" + "="*70)
    print("1.4: LAG DEPTH OPTIMIZATION")
    print("="*70)
    
    if model_params is None:
        model_params = config.LGBM_PARAMS
    
    # Test different lag depths for key features
    test_lags = [1, 2, 3, 5, 10, 15, 20]  # Test 1-20 day lags
    key_features = base_features[:10]  # Test on first 10 base features for efficiency
    
    print(f"Testing lag depths {test_lags} on {len(key_features)} key features")
    
    results = []
    for lag_depth in test_lags:
        print(f"\nTesting lag depth: {lag_depth}")
        
        # Create lag features for this depth
        lag_df = pd.DataFrame(X_train, columns=feature_names)
        for feature in key_features:
            if feature in lag_df.columns:
                lag_df[f"{feature}_lag_{lag_depth}"] = lag_df[feature].shift(lag_depth)
        
        # Drop rows with NaN from shifting
        lag_df = lag_df.dropna()
        if len(lag_df) < len(X_train) * 0.5:  # Skip if too many rows dropped
            print(f"  Skipping lag {lag_depth} - too many NaN values")
            continue
        
        # Create corresponding backtest features
        backtest_lag_df = pd.DataFrame(X_backtest, columns=feature_names)
        for feature in key_features:
            if feature in backtest_lag_df.columns:
                backtest_lag_df[f"{feature}_lag_{lag_depth}"] = backtest_lag_df[feature].shift(lag_depth)
        
        # Align data (remove NaN rows)
        backtest_lag_df = backtest_lag_df.dropna()
        
        # Train model
        model = model_class(**model_params)
        model.fit(lag_df.values, y_train[:len(lag_df)])
        
        # Predict and score
        predictions = model.predict(backtest_lag_df.values)
        score = model.score(backtest_lag_df.values, y_backtest[:len(backtest_lag_df)])
        ic = np.corrcoef(predictions, y_backtest[:len(backtest_lag_df)])[0, 1]
        
        results.append({
            'lag_depth': lag_depth,
            'score': score,
            'ic': ic,
            'n_features': lag_df.shape[1],
            'n_samples': lag_df.shape[0]
        })
        
        print(f"  Score: {score:.4f}, IC: {ic:.4f}")
    
    # Find best lag depth
    lag_df = pd.DataFrame(results).sort_values('score', ascending=False)
    print(f"\nLag depth optimization results:")
    print(lag_df.to_string(index=False))
    
    best_lag = lag_df.iloc[0]['lag_depth']
    print(f"\nBest lag depth: {best_lag} (Score: {lag_df.iloc[0]['score']:.4f})")
    
    return lag_df


def test_window_sizes(X_train, y_train, X_backtest, y_backtest, feature_names, base_features, model_class=lgb.LGBMRegressor, model_params=None):
    """
    Test different rolling window sizes for key features.
    """
    print("\n" + "="*70)
    print("1.4: WINDOW SIZE OPTIMIZATION")
    print("="*70)
    
    if model_params is None:
        model_params = config.LGBM_PARAMS
    
    # Test different window sizes
    test_windows = [3, 5, 10, 15, 20, 25, 30, 60]
    key_features = base_features[:5]  # Test on first 5 base features for efficiency
    
    print(f"Testing window sizes {test_windows} on {len(key_features)} key features")
    
    results = []
    for window in test_windows:
        print(f"\nTesting window size: {window}")
        
        # Create rolling features for this window
        roll_df = pd.DataFrame(X_train, columns=feature_names)
        for feature in key_features:
            if feature in roll_df.columns:
                roll_df[f"{feature}_roll_mean_{window}"] = roll_df[feature].rolling(window=window, min_periods=1).mean()
                roll_df[f"{feature}_roll_std_{window}"] = roll_df[feature].rolling(window=window, min_periods=1).std()
        
        # Drop rows with NaN from rolling
        roll_df = roll_df.dropna()
        
        # Create corresponding backtest features
        backtest_roll_df = pd.DataFrame(X_backtest, columns=feature_names)
        for feature in key_features:
            if feature in backtest_roll_df.columns:
                backtest_roll_df[f"{feature}_roll_mean_{window}"] = backtest_roll_df[feature].rolling(window=window, min_periods=1).mean()
                backtest_roll_df[f"{feature}_roll_std_{window}"] = backtest_roll_df[feature].rolling(window=window, min_periods=1).std()
        
        # Align data (remove NaN rows)
        backtest_roll_df = backtest_roll_df.dropna()
        
        # Train model
        model = model_class(**model_params)
        model.fit(roll_df.values, y_train[:len(roll_df)])
        
        # Predict and score
        predictions = model.predict(backtest_roll_df.values)
        score = model.score(backtest_roll_df.values, y_backtest[:len(backtest_roll_df)])
        ic = np.corrcoef(predictions, y_backtest[:len(backtest_roll_df)])[0, 1]
        
        results.append({
            'window_size': window,
            'score': score,
            'ic': ic,
            'n_features': roll_df.shape[1],
            'n_samples': roll_df.shape[0]
        })
        
        print(f"  Score: {score:.4f}, IC: {ic:.4f}")
    
    # Find best window size
    window_df = pd.DataFrame(results).sort_values('score', ascending=False)
    print(f"\nWindow size optimization results:")
    print(window_df.to_string(index=False))
    
    best_window = window_df.iloc[0]['window_size']
    print(f"\nBest window size: {best_window} (Score: {window_df.iloc[0]['score']:.4f})")
    
    return window_df


def create_comprehensive_interaction_terms(df, feature_names):
    """
    Create comprehensive interaction terms for feature expansion.
    """
    print("\n" + "="*70)
    print("1.4: COMPREHENSIVE INTERACTION FEATURE EXPANSION")
    print("="*70)
    
    # Get base features (non-engineered features)
    base_features = [f for f in feature_names if '_' not in f or f.count('_') == 1 and f.split('_')[1].isdigit()]
    base_features = [f for f in base_features if f in df.columns and f not in ['date_id', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']]
    
    print(f"Creating interaction terms from {len(base_features)} base features")
    
    interaction_count = 0
    
    # 1. All pairwise products
    print("Creating pairwise products...")
    for i, feat1 in enumerate(base_features[:15]):  # Limit to first 15 for computational efficiency
        for j, feat2 in enumerate(base_features[:15]):
            if i < j:  # Upper triangle only
                if feat1 in df.columns and feat2 in df.columns:
                    col_name = f"{feat1}_prod_{feat2}"
                    df[col_name] = df[feat1] * df[feat2]
                    interaction_count += 1
    
    # 2. All pairwise ratios
    print("Creating pairwise ratios...")
    for i, feat1 in enumerate(base_features[:15]):
        for j, feat2 in enumerate(base_features[:15]):
            if i < j:
                if feat1 in df.columns and feat2 in df.columns:
                    col_name = f"{feat1}_div_{feat2}"
                    df[col_name] = df[feat1] / (df[feat2] + 1e-6)
                    interaction_count += 1
    
    # 3. All pairwise differences
    print("Creating pairwise differences...")
    for i, feat1 in enumerate(base_features[:15]):
        for j, feat2 in enumerate(base_features[:15]):
            if i < j:
                if feat1 in df.columns and feat2 in df.columns:
                    col_name = f"{feat1}_minus_{feat2}"
                    df[col_name] = df[feat1] - df[feat2]
                    interaction_count += 1
    
    print(f"Added {interaction_count} comprehensive interaction features")
    return df


# ============================================================================
# MAIN EXECUTION
# ============================================================================

def compare_pipelines():
    """
    Compare the different feature pipelines.
    """
    print("\n" + "="*70)
    print("PHASE 1: BRONZE ENHANCEMENT & FEATURE OPTIMIZATION")
    print("="*70)
    
    # 1. Load and prepare base data
    print("\nLoading base data...")
    df = pd.read_csv(config.DATA_PATH)
    df = df.sort_values(by="date_id").reset_index(drop=True)
    
    # Store original columns
    original_cols = df.columns.tolist()
    print(f"Original data: {len(df)} rows, {len(original_cols)} columns")
    print(f"Original columns: {list(original_cols)}")
    
    # 1.1: Test 163rd Place Pipeline
    print("\n" + "="*70)
    print("TESTING 1.1: 163RD PLACE INTEGRATION")
    print("="*70)
    
    try:
        data_163rd = prepare_data_163rd(config.DATA_PATH, config)
        
        # Train LightGBM model
        X_train = data_163rd['X_train_scaled']
        y_train = data_163rd['train_era'][config.TARGET].values
        
        model_163rd = lgb.LGBMRegressor(**config.LGBM_PARAMS)
        model_163rd.fit(X_train, y_train)
        
        # Evaluate
        X_backtest = data_163rd['X_backtest_scaled']
        backtest_era = data_163rd['backtest_era']
        predictions_163rd = model_163rd.predict(X_backtest)
        
        results_163rd = evaluate_strategy_163rd(backtest_era, predictions_163rd, data_163rd, config, "163rd Place")
        
        print(f"163rd Place Results:")
        print(f"  IC: {results_163rd['ic']:+.4f}")
        print(f"  Score: {results_163rd['score']:.4f}")
        print(f"  Vol Ratio: {results_163rd['vol_ratio']:.2f}x {results_163rd['vol_ratio_status']}")
        print(f"  Sharpe: {results_163rd['strategy_sharpe']:.3f}")
        print(f"  Alpha: {results_163rd['net_alpha']:+.2f}%")
        
    except Exception as e:
        print(f"Error in 163rd Place pipeline: {e}")
    
    # 1.2: Test 261-feature pipeline
    print("\n" + "="*70)
    print("TESTING 1.2: 261-FEATURE PIPELINE")
    print("="*70)
    
    try:
        # Create a copy of the original data
        df_261 = df.copy()
        df_261 = create_full_261_feature_pipeline(df_261)
        
        # Prepare data (drop NA, split, scale)
        df_261 = df_261.dropna()
        
        TRAIN_END = len(df_261) - config.EXCLUDE_LAST_N_DAYS
        train_era = df_261.iloc[:TRAIN_END].copy()
        backtest_era = df_261.iloc[TRAIN_END:].copy()
        
        targets = ['forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
        exclude_cols = ['date_id'] + targets
        feature_cols = [col for col in df_261.columns if col not in exclude_cols and not col.startswith('vol_proxy')]
        
        X_train = train_era[feature_cols]
        X_backtest = backtest_era[feature_cols]
        y_train = train_era[config.TARGET].values
        
        # Scale features
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_backtest_scaled = scaler.transform(X_backtest)
        
        # Train model
        model_261 = lgb.LGBMRegressor(**config.LGBM_PARAMS)
        model_261.fit(X_train_scaled, y_train)
        
        # Evaluate
        predictions_261 = model_261.predict(X_backtest_scaled)
        
        # Use simple allocation for comparison (same as solution.py)
        v_cols = [col for col in backtest_era.columns if col.startswith('V')]
        if v_cols:
            train_vol_median = train_era[v_cols].abs().mean(axis=1).median()
            vol_scalar = train_vol_median / (backtest_era[v_cols].abs().mean(axis=1).values + 1e-8)
        else:
            vol_scalar = 1.0
        
        allocation_261 = 1.0 + (predictions_261 * config.BASE_MULTIPLIER * vol_scalar)
        allocation_261 = np.clip(allocation_261, 0.0, 2.0)
        
        # Calculate metrics
        market_daily_return = backtest_era['forward_returns'].values
        strategy_daily_return = allocation_261 * market_daily_return
        actual_returns = backtest_era[config.TARGET].values
        
        ic_261 = np.corrcoef(predictions_261, actual_returns)[0, 1]
        ann_strategy_return_261 = np.mean(strategy_daily_return) * 252 * 100
        ann_strategy_vol_261 = np.std(strategy_daily_return) * np.sqrt(252) * 100
        ann_market_vol_261 = np.std(market_daily_return) * np.sqrt(252) * 100
        vol_ratio_261 = ann_strategy_vol_261 / ann_market_vol_261 if ann_market_vol_261 > 0 else 0
        strategy_sharpe_261 = (np.mean(strategy_daily_return) * 252 * 100) / ann_strategy_vol_261 if ann_strategy_vol_261 > 0 else 0
        score_261 = strategy_sharpe_261 * (1.0 - max(0, vol_ratio_261 - config.MAX_VOL_RATIO) / 2.0)
        
        print(f"261-feature pipeline Results:")
        print(f"  Total Features: {len(feature_cols)}")
        print(f"  IC: {ic_261:+.4f}")
        print(f"  Score: {score_261:.4f}")
        print(f"  Vol Ratio: {vol_ratio_261:.2f}x")
        print(f"  Sharpe: {strategy_sharpe_261:.3f}")
        
    except Exception as e:
        print(f"Error in 261-feature pipeline: {e}")
        import traceback
        traceback.print_exc()
    
    # 1.2: Test simplified 1187-feature pipeline (due to computational constraints)
    print("\n" + "="*70)
    print("TESTING 1.2: SIMPLIFIED 1187-FEATURE PIPELINE")
    print("="*70)
    
    try:
        # Create a simplified version with fewer base features for testing
        df_1187 = df.copy()
        
        # Use only key features for demonstration
        key_base_features = [col for col in df.columns if col.startswith(('M', 'V', 'E', 'P'))][:20]
        print(f"Testing with {len(key_base_features)} key base features")
        
        # Create simplified pipeline
        df_1187 = create_lag_features_1187(df_1187, key_base_features, [1, 2, 5, 10])
        df_1187 = create_rolling_features_1187(df_1187, key_base_features, [5, 10], ['mean', 'std', 'max'])
        df_1187, rank_cols, zscore_cols = create_rank_zscore_features_1187(df_1187, key_base_features)
        
        # Simplified interaction features
        for c in ['M4', 'M1', 'E1', 'V2']:
            if c in df_1187.columns and f'{c}_RANK' in df_1187.columns:
                df_1187[f"{c}_x_{c}_RANK"] = df_1187[c] * df_1187[f'{c}_RANK']
        
        # Prepare data
        df_1187 = df_1187.dropna()
        
        TRAIN_END = len(df_1187) - config.EXCLUDE_LAST_N_DAYS
        train_era = df_1187.iloc[:TRAIN_END].copy()
        backtest_era = df_1187.iloc[TRAIN_END:].copy()
        
        targets = ['forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
        exclude_cols = ['date_id'] + targets
        feature_cols = [col for col in df_1187.columns if col not in exclude_cols and not col.startswith('vol_proxy')]
        
        print(f"Total features in simplified 1187 pipeline: {len(feature_cols)}")
        
        X_train = train_era[feature_cols]
        X_backtest = backtest_era[feature_cols]
        y_train = train_era[config.TARGET].values
        
        # Scale features
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_backtest_scaled = scaler.transform(X_backtest)
        
        # Train model
        model_1187 = lgb.LGBMRegressor(**config.LGBM_PARAMS)
        model_1187.fit(X_train_scaled, y_train)
        
        # Evaluate
        predictions_1187 = model_1187.predict(X_backtest_scaled)
        
        # Use simple allocation for comparison
        v_cols = [col for col in backtest_era.columns if col.startswith('V')]
        if v_cols:
            train_vol_median = train_era[v_cols].abs().mean(axis=1).median()
            vol_scalar = train_vol_median / (backtest_era[v_cols].abs().mean(axis=1).values + 1e-8)
        else:
            vol_scalar = 1.0
        
        allocation_1187 = 1.0 + (predictions_1187 * config.BASE_MULTIPLIER * vol_scalar)
        allocation_1187 = np.clip(allocation_1187, 0.0, 2.0)
        
        # Calculate metrics
        market_daily_return = backtest_era['forward_returns'].values
        strategy_daily_return = allocation_1187 * market_daily_return
        actual_returns = backtest_era[config.TARGET].values
        
        ic_1187 = np.corrcoef(predictions_1187, actual_returns)[0, 1]
        ann_strategy_return_1187 = np.mean(strategy_daily_return) * 252 * 100
        ann_strategy_vol_1187 = np.std(strategy_daily_return) * np.sqrt(252) * 100
        ann_market_vol_1187 = np.std(market_daily_return) * np.sqrt(252) * 100
        vol_ratio_1187 = ann_strategy_vol_1187 / ann_market_vol_1187 if ann_market_vol_1187 > 0 else 0
        strategy_sharpe_1187 = (np.mean(strategy_daily_return) * 252 * 100) / ann_strategy_vol_1187 if ann_strategy_vol_1187 > 0 else 0
        score_1187 = strategy_sharpe_1187 * (1.0 - max(0, vol_ratio_1187 - config.MAX_VOL_RATIO) / 2.0)
        
        print(f"Simplified 1187-feature pipeline Results:")
        print(f"  Total Features: {len(feature_cols)}")
        print(f"  IC: {ic_1187:+.4f}")
        print(f"  Score: {score_1187:.4f}")
        print(f"  Vol Ratio: {vol_ratio_1187:.2f}x")
        print(f"  Sharpe: {strategy_sharpe_1187:.3f}")
        
    except Exception as e:
        print(f"Error in 1187-feature pipeline: {e}")
        import traceback
        traceback.print_exc()
    
    print("\n" + "="*70)
    print("PHASE 1: PIPELINE COMPARISON COMPLETE")
    print("="*70)
    
    return {
        'original_features': len(original_cols),
        'pipeline_163rd_features': len(data_163rd['feature_cols']) if 'data_163rd' in locals() else 0,
        'pipeline_261_features': len(feature_cols) if 'feature_cols' in locals() else 0,
        'pipeline_1187_features': len(feature_cols) if 'feature_cols' in locals() else 0,
    }


if __name__ == "__main__":
    # Run the comparison
    results = compare_pipelines()
    
    print("\nFeature Count Summary:")
    print(f"  Original: {results['original_features']} features")
    print(f"  163rd Place: {results['pipeline_163rd_features']} features")
    print(f"  261-feature: {results['pipeline_261_features']} features")
    print(f"  1187-feature (simplified): {results['pipeline_1187_features']} features")